### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by ItzFireable**
This PR updates the UI of the main menu, and result screen (slight adjustments). It also creates a basic settings menu, which can be used as a base.

Notes:
- Result screen needs some changes, like the background image not showing and graph not showing all misses.
- Main menu does not have a template for the top play or update log yet. However, these 2 will be added later on as both are not required at this moment.

### CODE REVIEW

**Comment by ItzFireable** [comment]
This is the first part towards new UI 💗

**Comment by ItzFireable** [comment]
- Added the ratio to bottom right of total judgements.
- Added result in the middle of banner (needs to be scripted, i can't think of a good, **efficient** way to do that).

**Comment by ItzFireable** [comment]
- Redesigned recently added gameplay screen.
- Fixed a few design flaws on result screen.

**Comment by ItzFireable** [comment]
- Added Math.format to Math util.
- Utilized Math.format in larger numbers like score in result and gameplay screens.

**Comment by thenerdie** [comment]
Just merged keep doing what ur doing

**Pull request merged**
